import glob
import os
import sys

from WriteFile import WriteFile

header = """\
# Don't edit Makefile!  Use conf-* for configuration.
#
# Generated by spac see http://untroubled.org/spac/

SHELL=/bin/sh

"""

def write(ruleset, filename='Makefile'):
	names = list(ruleset.keys())
	names.sort()

	makefile = WriteFile('Makefile')
	makefile.write(header)
	#makefile.write("everything: %s\n\n" % ' '.join(names))

	# Make sure the DEFAULT rule goes on top
	try:
		names.remove(('DEFAULT',))
	except KeyError:
		pass
	else:
		makefile.write(str(ruleset[('DEFAULT',)]))
		makefile.write('\n')
	for name in names:
		makefile.write(str(ruleset[name]))
		makefile.write('\n')
	makefile.close()
