#!/usr/bin/python2
import string
import sys

def die(msg):
	raise SystemExit, "spac-dist: Error: %s" % msg

try: version = string.strip(open('VERSION').readline())
except IOError:	die("Missing VERSION file for building distribution.")

try: (package,version) = string.split(version, ' ')
except ValueError: die("Invalid VERSION file")

import dist
dist.main(package, version)
