#!/usr/bin/python3
import os

def rmlist(listname, type):
	try:
		list = [ l.rstrip() for l in file(listname) ]
	except IOError:
		return
	for filename in list:
		try:
			os.unlink(filename)
			print("Removed %s file '%s'" % (type, filename))
		except: pass
rmlist('TARGETS', 'target')
rmlist('AUTOFILES', 'automatic')
