#!/usr/bin/python2
import sys

def die(msg):
	raise SystemExit, "spac-dist: Error: %s" % msg

try: version = file('VERSION').readline().strip()
except IOError:	die("Missing VERSION file for building distribution.")

try: (package,version) = version.split(' ')
except ValueError: die("Invalid VERSION file")

import dist
dist.main(package, version)
